Awesome Books: Project 1
rolandfbk/awesome-books pull request #1
Opened 2022-04-18 20:30 UTC by V0pe

### Awesome Books: Plan HTML and CSS

In this project, the following was carried out,

- [ ] Add the markup for the landing page.
- [ ] Create the new book class and append it to the book list.
- [ ] Add the local storage and retrieve the data from the localstorage. 
- [ ] Append the new and updated data to the book list section.
- [ ] Implement the remove button that removes each item from the book list.

2022-04-18 21:02 UTC, prolajumokeoni requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️  Add button works
✔️  Good PR and Description



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_Check inline comments_
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-18 21:02 UTC, prolajumokeoni commented on README.md
> +## Author
OPTIONAL 
- [ ] Kindly add social media  links of other collaborators

2022-04-18 21:02 UTC, prolajumokeoni commented on index.js
> +}
- [ ] When I click on the remove button: 
- The right book is not removed from the collection. 
- The right book does not disappear from the page. 
### Kindly fix this as this is part of the  project requirements 👍🏿 
- [ ] Kindly ensure that data is preserved in the browser's memory by using [localStorage](https://github.com/microverseinc/curriculum-html-css/blob/main/local_storage.md) after removing a book.
.

2022-04-19 11:42 UTC, EricMbouwe approved these changes
### Hi @V0pe, 

# Status: Approved ✔️
Excellent job on this project. Keep it up 👏
Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-19 12:01 UTC, merged